head_camera:
  enable_zmq: true
  zmq_port: 55555
  enable_webrtc: true
  webrtc_port: 60001
  webrtc_codec: h264
  type: realsense
  image_shape:
  - 480
  - 640
  binocular: false
  fps: 30
  video_id: 0
  serial_number: 937622072750
  physical_path: null
